const userActionType = {
  SET_CURRENT_USER: "SET_CURRENT_USER",
  GOOGLE_SIGN_IN_START: "GOOGLE_SIGN_IN_START",
  EMAIL_SIGN_IN_START: "EMAIL_SIGN_IN_START",
  SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
  SIGN_IN_FAILURE: "SIGN_IN_FAILURE",
  USER_SIGN_OUT_START: "USER_SIGN_OUT_START",
  USER_SIGN_OUT_FAILURE: "USER_SIGN_OUT_FAILURE",
  USER_SIGN_OUT_SUCCESS: "USER_SIGN_OUT_SUCCESS",
  SIGN_UP_START: "SIGN_UP_START",
  SIGN_UP_SUCCESS: "SIGN_UP_SUCCESS",
  SIGN_UP_FAILURE: "SIGN_UP_FAILURE",
  CHECK_SEESION: "CHECK_SEESION",
  SET_SEESION: "SET_SEESION",
};

export default userActionType;
